import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase,loginEmail} from './supabase';
import {LogOut,Plus,Trash2,Pencil,WalletCards,Users,FolderKanban,RefreshCcw,KeyRound,ChevronDown,ChevronRight,Save,Copy,CheckCircle2,AlertTriangle,ShoppingBasket,CalendarDays} from 'lucide-react';
import './styles.css';

const money=(n,c='PHP')=>new Intl.NumberFormat('en-PH',{style:'currency',currency:c,minimumFractionDigits:2}).format(Number(n||0));
const isoWeekStart=(d=new Date())=>{const x=new Date(d);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);x.setHours(0,0,0,0);return x.toISOString().slice(0,10)};
const emptyItem={name:'',quantity:'',unit_id:'',unit_text:'',price:'',currency:'PHP',remarks:''};
function Toast({toast}){return toast?<div className={`toast ${toast.type||''}`}>{toast.type==='error'?<AlertTriangle/>:<CheckCircle2/>}{toast.msg}</div>:null}

function Login({onToast}){const [username,setUsername]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);async function login(e){e.preventDefault();setLoading(true);const {error}=await supabase.auth.signInWithPassword({email:loginEmail(username),password});setLoading(false);if(error) onToast(error.message,'error')}
return <div className="authShell"><div className="brandPanel"><div className="brandIcon"><ShoppingBasket/></div><h1>ExpenseWise PH</h1><p>Weekly grocery & goods expense management for shared households and teams.</p><div className="featurePills"><span>PHP / USD</span><span>Weekly budgets</span><span>Shared categories</span></div></div><form className="loginCard" onSubmit={login}><div><small>SECURE WORKSPACE</small><h2>Welcome back</h2><p>Sign in with the username and password provided by your admin.</p></div><label>Username<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/></label><button className="primary" disabled={loading}>{loading?'Signing in…':'Sign in'}</button></form></div>}

function App(){const[session,setSession]=useState(null),[profile,setProfile]=useState(null),[toast,setToast]=useState(null),[tab,setTab]=useState('expenses');useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);useEffect(()=>{if(!session){setProfile(null);return}supabase.from('expense_profiles').select('*').eq('id',session.user.id).single().then(({data,error})=>{if(error)notify(error.message,'error');else setProfile(data)})},[session]);function notify(msg,type='ok'){setToast({msg,type});setTimeout(()=>setToast(null),3200)}if(!session)return <><Login onToast={notify}/><Toast toast={toast}/></>;if(!profile)return <div className="center">Loading workspace…</div>;return <div><header><div className="logo"><span><ShoppingBasket/></span><div><b>ExpenseWise PH</b><small>Weekly Expense Manager</small></div></div><nav><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}><WalletCards/>Expenses</button>{profile.role==='admin'&&<><button className={tab==='categories'?'active':''} onClick={()=>setTab('categories')}><FolderKanban/>Categories</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><Users/>Users</button></>}</nav><div className="account"><div><b>{profile.full_name}</b><small>{profile.role}</small></div><button className="iconBtn" onClick={()=>supabase.auth.signOut()} title="Logout"><LogOut/></button></div></header><main>{tab==='expenses'?<ExpenseWorkspace profile={profile} notify={notify}/>:tab==='categories'?<CategoryAdmin notify={notify}/>:<UserAdmin notify={notify}/>}</main><Toast toast={toast}/></div>}

function ExpenseWorkspace({profile,notify}){const[week,setWeek]=useState(isoWeekStart()),[categories,setCategories]=useState([]),[categoryId,setCategoryId]=useState(''),[sections,setSections]=useState([]),[items,setItems]=useState([]),[units,setUnits]=useState([]),[budgets,setBudgets]=useState({PHP:'',USD:''}),[joinCode,setJoinCode]=useState(''),[loading,setLoading]=useState(true);
async function loadBase(){setLoading(true);const[{data:cats,error:ce},{data:us}]=await Promise.all([supabase.from('expense_categories').select('*').order('name'),supabase.from('expense_units').select('*').order('name')]);if(ce)notify(ce.message,'error');setCategories(cats||[]);setUnits(us||[]);if(!categoryId&&cats?.length)setCategoryId(cats[0].id);setLoading(false)}
async function loadWeek(){if(!categoryId)return;const[{data:ss},{data:ii},{data:bb}]=await Promise.all([supabase.from('expense_list_sections').select('*').eq('category_id',categoryId).eq('week_start',week).order('sort_order'),supabase.from('expense_items').select('*').eq('category_id',categoryId).eq('week_start',week).order('sort_order'),supabase.from('expense_weekly_budgets').select('*').eq('category_id',categoryId).eq('week_start',week)]);setSections(ss||[]);setItems(ii||[]);const b={PHP:'',USD:''};(bb||[]).forEach(x=>b[x.currency]=x.amount);setBudgets(b)}
useEffect(()=>{loadBase()},[]);useEffect(()=>{loadWeek()},[categoryId,week]);
const totals=useMemo(()=>items.reduce((a,x)=>(a[x.currency]=(a[x.currency]||0)+Number(x.price||0),a),{PHP:0,USD:0}),[items]);
async function join(){const code=joinCode.trim();if(!code)return;const {data,error}=await supabase.rpc('expense_join_category_by_code',{p_code:code});if(error)return notify(error.message,'error');notify(`Joined ${data}`);setJoinCode('');loadBase()}
async function saveBudget(currency){const amount=Number(budgets[currency]||0);const {error}=await supabase.from('expense_weekly_budgets').upsert({category_id:categoryId,week_start:week,currency,amount},{onConflict:'category_id,week_start,currency'});error?notify(error.message,'error'):notify(`${currency} budget saved`)}
async function addSection(){const title=prompt('List title / subtitle (example: DALI Everyday Grocery Receipt)');if(!title?.trim())return;const {error}=await supabase.from('expense_list_sections').insert({category_id:categoryId,week_start:week,title:title.trim(),sort_order:sections.length});if(error)notify(error.message,'error');else loadWeek()}
async function deleteSection(id){if(!confirm('Delete this list title and all items under it?'))return;const {error}=await supabase.from('expense_list_sections').delete().eq('id',id);if(error)notify(error.message,'error');else loadWeek()}
async function addItem(section_id){const {error}=await supabase.from('expense_items').insert({name:'New item',quantity:null,unit_id:null,unit_text:null,price:null,currency:'PHP',remarks:null,category_id:categoryId,section_id,week_start:week,sort_order:items.length});if(error)notify(error.message,'error');else loadWeek()}
async function patchItem(id,patch){const {error}=await supabase.from('expense_items').update(patch).eq('id',id);if(error)notify(error.message,'error');else setItems(v=>v.map(x=>x.id===id?{...x,...patch}:x))}
async function deleteItem(id){if(!confirm('Delete this item?'))return;const{error}=await supabase.from('expense_items').delete().eq('id',id);if(error)notify(error.message,'error');else setItems(v=>v.filter(x=>x.id!==id))}
async function addUnit(){const name=prompt('New unit name (example: kilo, litre, pack, pc)');if(!name?.trim())return;const{data,error}=await supabase.from('expense_units').insert({name:name.trim()}).select().single();if(error)notify(error.message,'error');else{setUnits(v=>[...v,data].sort((a,b)=>a.name.localeCompare(b.name)));notify('Unit added')}}
if(loading)return <div className="center">Loading categories…</div>;
return <><section className="pageHead"><div><small>WEEKLY CONTROL CENTER</small><h1>Expenses & Budget</h1><p>Track purchases, grouped receipts and remaining budget by week.</p></div><div className="weekPick"><CalendarDays/><input type="date" value={week} onChange={e=>setWeek(e.target.value)}/><span>week start</span></div></section>
{!categories.length?<section className="empty"><FolderKanban/><h2>No category access yet</h2><p>Enter the share code provided by your admin.</p><div className="join"><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="CATEGORY CODE"/><button className="primary" onClick={join}><KeyRound/>Join category</button></div></section>:<>
<div className="toolbar"><select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><div className="join compact"><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase())} placeholder="Share code"/><button onClick={join}><KeyRound/>Join</button></div><button onClick={addSection}><Plus/>Add list title</button></div>
<div className="metricGrid"><Metric title="PHP Expenses" value={money(totals.PHP,'PHP')} sub={`Budget ${money(budgets.PHP||0,'PHP')}`} /><Metric title="PHP Remaining" value={money(Number(budgets.PHP||0)-totals.PHP,'PHP')} sub={Number(budgets.PHP||0)&&totals.PHP>Number(budgets.PHP)?'Over budget':'Available balance'} danger={Number(budgets.PHP||0)&&totals.PHP>Number(budgets.PHP)}/><Metric title="USD Expenses" value={money(totals.USD,'USD')} sub={`Budget ${money(budgets.USD||0,'USD')}`}/><Metric title="USD Remaining" value={money(Number(budgets.USD||0)-totals.USD,'USD')} sub="Separate currency total" danger={Number(budgets.USD||0)&&totals.USD>Number(budgets.USD)}/></div>
<section className="budgetBar"><b>Weekly Budget</b><BudgetInput c="PHP" value={budgets.PHP} set={v=>setBudgets(x=>({...x,PHP:v}))} save={()=>saveBudget('PHP')}/><BudgetInput c="USD" value={budgets.USD} set={v=>setBudgets(x=>({...x,USD:v}))} save={()=>saveBudget('USD')}/></section>
{sections.length===0?<section className="empty small"><ShoppingBasket/><h3>No lists for this week</h3><p>Add a list title such as a store receipt, market list, pharmacy or household supplies.</p><button className="primary" onClick={addSection}><Plus/>Add first list</button></section>:sections.map((s,idx)=><Section key={s.id} s={s} idx={idx} items={items.filter(i=>i.section_id===s.id)} units={units} addUnit={addUnit} addItem={()=>addItem(s.id)} patchItem={patchItem} deleteItem={deleteItem} deleteSection={()=>deleteSection(s.id)}/>) }
<div className="grand"><div><small>GRAND TOTAL — PHP</small><b>{money(totals.PHP,'PHP')}</b></div><div><small>GRAND TOTAL — USD</small><b>{money(totals.USD,'USD')}</b></div><span>Currencies are intentionally totalled separately.</span></div></>}
</>}
function Metric({title,value,sub,danger}){return <div className={`metric ${danger?'danger':''}`}><small>{title}</small><strong>{value}</strong><span>{sub}</span></div>}
function BudgetInput({c,value,set,save}){return <div className="budgetInput"><span>{c}</span><input type="number" min="0" step="0.01" value={value} onChange={e=>set(e.target.value)} placeholder="0.00"/><button onClick={save}><Save/></button></div>}
function Section({s,idx,items,units,addUnit,addItem,patchItem,deleteItem,deleteSection}){const[open,setOpen]=useState(true);const subtotal=items.reduce((a,x)=>(a[x.currency]=(a[x.currency]||0)+Number(x.price||0),a),{PHP:0,USD:0});return <section className="receipt"><div className="receiptHead"><button className="chev" onClick={()=>setOpen(!open)}>{open?<ChevronDown/>:<ChevronRight/>}</button><div><small>LIST {idx+1}</small><h3>{s.title}</h3></div><div className="subtotal"><span>{money(subtotal.PHP,'PHP')}</span><span>{money(subtotal.USD,'USD')}</span></div><button className="iconBtn dangerBtn" onClick={deleteSection}><Trash2/></button></div>{open&&<><div className="tableWrap"><table><thead><tr><th>Item / Goods</th><th>Qty</th><th>Unit</th><th>Currency</th><th>Price</th><th>Remarks / Notes</th><th></th></tr></thead><tbody>{items.map(i=><ItemRow key={i.id} item={i} units={units} patch={patchItem} del={deleteItem}/>)}</tbody></table></div><div className="receiptFoot"><button onClick={addItem}><Plus/>Add item</button><button onClick={addUnit}><Plus/>Add unit</button><div><b>Subtotal:</b> {money(subtotal.PHP,'PHP')} &nbsp; · &nbsp; {money(subtotal.USD,'USD')}</div></div></>}</section>}
function ItemRow({item,units,patch,del}){const set=(k,v)=>patch(item.id,{[k]:v===''?null:v});return <tr><td><input value={item.name||''} onChange={e=>set('name',e.target.value)} placeholder="Item name"/></td><td><input className="sm" type="number" step="any" min="0" value={item.quantity??''} onChange={e=>set('quantity',e.target.value)}/></td><td><select value={item.unit_id||''} onChange={e=>set('unit_id',e.target.value)}><option value="">— none —</option>{units.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></td><td><select value={item.currency||'PHP'} onChange={e=>set('currency',e.target.value)}><option>PHP</option><option>USD</option></select></td><td><input className="price" type="number" step="0.01" min="0" value={item.price??''} onChange={e=>set('price',e.target.value)} placeholder="0.00"/></td><td><input value={item.remarks||''} onChange={e=>set('remarks',e.target.value)} placeholder="Optional notes"/></td><td><button className="iconBtn dangerBtn" onClick={()=>del(item.id)}><Trash2/></button></td></tr>}

function CategoryAdmin({notify}){const[cats,setCats]=useState([]),[name,setName]=useState('');async function load(){const{data,error}=await supabase.from('expense_categories').select('*').order('created_at',{ascending:false});error?notify(error.message,'error'):setCats(data||[])}useEffect(()=>{load()},[]);async function create(){if(!name.trim())return;const{error}=await supabase.from('expense_categories').insert({name:name.trim()});if(error)notify(error.message,'error');else{setName('');notify('Category created');load()}}async function reset(id){if(!confirm('Reset ALL expense lists, items and budgets in this category? This cannot be undone.'))return;const{error}=await supabase.rpc('expense_admin_reset_category',{p_category_id:id});error?notify(error.message,'error'):notify('Category data reset')}
return <><section className="pageHead"><div><small>ADMIN</small><h1>Category Management</h1><p>Create controlled expense workspaces and share their access code.</p></div></section><section className="adminCard"><div className="createRow"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Category name e.g. Home Grocery"/><button className="primary" onClick={create}><Plus/>Create category</button></div><div className="cardList">{cats.map(c=><div className="categoryCard" key={c.id}><div><b>{c.name}</b><small>Created {new Date(c.created_at).toLocaleDateString()}</small></div><code>{c.share_code}</code><button onClick={()=>{navigator.clipboard.writeText(c.share_code);notify('Code copied')}}><Copy/>Copy code</button><button className="dangerBtn" onClick={()=>reset(c.id)}><RefreshCcw/>Reset data</button></div>)}</div></section></>}

function UserAdmin({notify}){const[name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[creating,setCreating]=useState(false),[users,setUsers]=useState([]);async function load(){const{data,error}=await supabase.from('expense_profiles').select('id,full_name,username,role,created_at').order('created_at',{ascending:false});error?notify(error.message,'error'):setUsers(data||[])}useEffect(()=>{load()},[]);async function create(){if(!name||!username||password.length<8)return notify('Enter name, username and a password of at least 8 characters.','error');setCreating(true);const{error}=await supabase.functions.invoke('expense-create-user',{body:{full_name:name,username,password}});setCreating(false);if(error)return notify(error.message,'error');notify('User created');setName('');setUsername('');setPassword('');load()}
return <><section className="pageHead"><div><small>ADMIN</small><h1>User Management</h1><p>Create login credentials. Users join expense categories using the category share code.</p></div></section><section className="adminCard"><div className="userForm"><label>Full name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Username<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>Temporary password<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="primary" disabled={creating} onClick={create}><Plus/>{creating?'Creating…':'Add user'}</button></div><div className="tableWrap"><table><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Created</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name}</b></td><td>{u.username}</td><td><span className="rolePill">{u.role}</span></td><td>{new Date(u.created_at).toLocaleDateString()}</td></tr>)}</tbody></table></div></section></>}
createRoot(document.getElementById('root')).render(<App/>);
